#!/bin/sh

rightmenu="  Applications
$(xdg-xmenu | sed -e 's/^/	/')

  Shutdown			poweroff || sudo poweroff
  Reboot			reboot || sudo reboot
  Suspend			dwm-util lock; loginctl suspend || systemctl suspend

  Reload dwm		dwmc rquit
  Log out			dwmc quit"

appsmenu="  Terminal			$TERMINAL"
command -v $BROWSER > /dev/null 2>&1    && appsmenu="$appsmenu
  Web				$BROWSER"
command -v mpv > /dev/null 2>&1         && appsmenu="$appsmenu
  Media			mpv"
command -v $FILEBROWSER > /dev/null 2>&1 && appsmenu="$appsmenu
  Files			$FILEBROWSER"
command -v discord > /dev/null 2>&1     && appsmenu="$appsmenu
ﭮ  Discord			discord"
command -v spotify > /dev/null 2>&1     && appsmenu="$appsmenu
  Spotify			if pidof spotify; then dwmc toggleview 7; else spotify; fi"
command -v thunderbird > /dev/null 2>&1 && appsmenu="$appsmenu
  Mail				thunderbird"

contextmenu="  Fullscreen		dwmc togglefullscr
  Floating			dwmc togglefloating
  Zoom				dwmc zoom
  Close			dwmc killclient"


case $1 in
    # 1) rofi -show drun -config ~/.config/rofi/apps.rasi -fullscreen ;;
    # 1) xdg-xmenu | xmenu -p 0x0 | sh ;;
    1) pidof skippy-xd || skippy-xd > /dev/null 2>&1 ;;
    2) echo "$appsmenu" | xmenu -p 0x0:current | sh ;;
    3) echo "$rightmenu" | xmenu -p 0x0:current | sh ;;
    "context") echo "$contextmenu" | xmenu | sh ;;
esac

nice xdg-xmenu -u &
