#!/bin/bash

statusline=""

add_block () {
	content="$1"
	index="$2"
	nmatch="$3"

	if ! [ -z "$content" ] && ( [ -z "$nmatch" ] || ! [ "$content" = "$nmatch" ] ); then
    	statusline="$statusline\x0$index $content |"
	else
    	statusline="$statusline\x0$index"
	fi
}

help () {
    echo "Options for $0:"
    echo "    status: prints the current status to stdout"
    echo "    loop:   set status to WM_NAME in a loop"
    echo "    update: immediatly update status in WM_NAME"
    echo "    action: execute action (STATUSCMD and BUTTON give block and mouse button)"
}

loop () {
    (pa_loop) &

    while true; do
        set_status
        sleep 5 2> /dev/null
    done
}

set_status () {
    moonctl status "$(get_status)" || exit
}

### BLOCK FUNCTIONS

pa_volume () {
    pactl get-sink-volume @DEFAULT_SINK@ | grep "Volume" | sed 's/.*\/\s*\(.*\) \s*\/.*/\1/;'
}

pa_muted () {
    if pactl get-sink-mute @DEFAULT_SINK@ | grep no > /dev/null; then
        return 1
    else
        return 0
    fi
}

pa_loop () {
    volume="$(pa_volume)"
    pactl subscribe | grep --line-buffered "Event 'change' on sink" | while read line; do
        temp="$(pa_volume)"
        if [ "$volume" != "$temp" ]; then
            set_status
        fi
    done
}

volume () {
    if [ "$MOONWM_NERDFONT" = "0" ]; then
        icon=''
    elif pa_muted; then
        icon='婢 '
    else
        icon='墳 '
    fi
    printf "%s%s%%" "$icon" "$(pa_volume)"
}

timedate () {
    if [ "$MOONWM_NERDFONT" = "0" ]; then
        icon=''
    else
        icon=' '
    fi
    printf "%s%s" "$icon" "$(date +%R)"
}

### CUSTOM STATUS AND ACTIONS

get_status () {
    statusline=""

    add_block "$(volume)" 1
    add_block "$(timedate)" 2

    printf "$statusline|\n"
}

action () {
    case "$STATUSCMDN" in
        0)
            case $BUTTON in
                1) pademelon-tools volume --mute toggle;;
                4) pademelon-tools volume --inc 5;;
                5) pademelon-tools volume --dec 5;;
            esac;;
        1)
            case $BUTTON in
                1) notify-send -a "$(date)" "$(cal -n 2)";;
            esac;;
    esac
}


case $1 in
    status)
        get_status;;
    update)
        set_status;;
    loop)
        loop;;
    action)
        action;;
    '')
        echo "Defaulting to 'loop'"
        echo "For other options see '$0 help'"
        loop;;
    help)
        help;;
esac
