#!/bin/sh

rightmenu="  Applications
$(moonwm-xdg-xmenu -l | sed -e 's/^/	/')

  Shutdown			poweroff || sudo poweroff
  Reboot			reboot || sudo reboot
  Suspend			moonwm-util lock; loginctl suspend || systemctl suspend

  Reload MoonWM	moonie restartlaunched
  Log out			moonie quit"

appsmenu="  Terminal			$TERMINAL"
command -v $BROWSER > /dev/null 2>&1    && appsmenu="$appsmenu
  Web				$BROWSER"
command -v mpv > /dev/null 2>&1         && appsmenu="$appsmenu
  Media			mpv"
command -v $FILEMANAGER > /dev/null 2>&1 && appsmenu="$appsmenu
  Files			$FILEMANAGER"
command -v discord > /dev/null 2>&1     && appsmenu="$appsmenu
ﭮ  Discord			discord"
command -v discord-canary > /dev/null 2>&1     && appsmenu="$appsmenu
ﭮ  Discord [c]		discord-canary"
command -v spotify > /dev/null 2>&1     && appsmenu="$appsmenu
  Spotify			if pidof spotify; then moonie toggleview 7; else spotify; fi"
command -v thunderbird > /dev/null 2>&1 && appsmenu="$appsmenu
  Mail				thunderbird"

contextmenu="  Close			close
ﭔ  Resize			resize
  Floating			float
  Fullscreen		fullscreen

   More
	  Close multiple		closemult
	  Kill process			kill"


important_msg () {
    xsetroot -name "important:$1 "
}

important_msg_close () {
    xsetroot -name "important:close"
    command -v "$MOONWM_STATUSCMD" 2>/dev/null \
        && "$MOONWM_STATUSCMD" update
}

context () {
    selection="$(printf "$contextmenu" | xmenu -i)"
    [ -z "$selection" ] && exit
    if [ "$1" = select ] && [ "$selection" != closemult ]; then
        case $selection in
            close)
                important_msg "Select a window to close." ;;
            resize)
                important_msg "Select a window to resize." ;;
            float)
                important_msg "Select a window to float/unfloat." ;;
            fullscreen)
                important_msg "Select a window enter/exit fullscreen." ;;
            kill)
                important_msg "Select a window to kill its process." ;;
        esac
        wid="$(slop -b 0 -f %i)"
        important_msg_close
        [ -z "$wid" ] && exit
        [ "$wid" = "$(xdotool search --maxdepth 0 --name '')" ] && exit
        xdotool get_desktop_for_window 1716
        timeout -k 3s 3s xdotool windowactivate --sync "$wid" || exit
    fi
    case $selection in
        close) moonie killclient ;;
        resize) moonie rioresize ;;
        float) moonie togglefloating ;;
        fullscreen) moonie togglefullscr ;;
        kill) kill "$(xdotool getwindowfocus getwindowpid)" ;;
        closemult)
            while [ 1 = 1 ]; do
                important_msg "Select multiple windows to close; Exit with <Esc> or right click."
                wid="$(slop -b 0 -f %i)"
                important_msg_close
                [ -z "$wid" ] && exit
                timeout -k 3s 3s xdotool windowclose "$wid"
            done
            ;;
    esac
}

layouts () {
    moonie setlayout "$(layouts_classic)"
}

layouts_classic () {
    moonie printlayouts | nl -v0 -w1 | sed 's/\s*[a-z]*$//;s/\([[:digit:]]*\)\t\(.*\)/\2\t\1/' | xmenu -i
}

menupos () {
    if ! [ "$MOONWM_TOPBAR" = 0 ]; then
        echo -p 0x0:current
    fi
}


case $1 in
    # 1) rofi -show drun -config ~/.config/rofi/apps.rasi -fullscreen ;;
    # 1) moonwm-xdg-xmenu | xmenu -p 0x0 | sh ;;
    1) pidof skippy-xd || skippy-xd > /dev/null 2>&1 ;;
    2) echo "$appsmenu" | xmenu -i $(menupos) | sh ;;
    3) echo "$rightmenu" | xmenu $(menupos) | sh ;;
    context) context select ;;
    context-client) context client ;;
    context-select) context select ;;
    layouts)
        layouts ;;
    layouts-classic)
        layouts_classic ;;
esac

