#!/bin/sh

options="\
### TAGS AND MONITORS ###
     Select tag                                     MOD + { 1 - 9 }
     Toggle tag                                     MOD + Control + { 1 - 9 }
     Move window to tag                             MOD + Shift + { 1 - 9 }
     Toggle tag on window                           MOD + Shift + Control + { 1 - 9 }
     View all tags                                  MOD + 0                            :moonctl viewall
     Window on all tags                             MOD + Shift + 0                    :moonctl tagall
     Switch to previously selected tags             MOD + Tab
     Switch to next occupied tag                    MOD + Shift + Tab                  :moonctl shiftviewclients +1
     Switch to previous occupied tag                MOD + Control + Tab                :moonctl shiftviewclients -1
     Switch to previous tag                         MOD + comma                        :moonctl shiftviewclients -1
     Switch to next tag                             MOD + period                       :moonctl shiftviewclients +1
     Focus previous monitor                         MOD + Prior                        :moonctl focusmon +1
     Move window to previous monitor                MOD + Shift + Prior                :moonctl tagmon +1
     Move window to previous monitor (keep tags)    MOD + Control + Prior              :moonctl tagmonkt +1
     Focus next monitor                             MOD + Next                         :moonctl focusmon -1
     Move window to next monitor                    MOD + Shift + Next                 :moonctl tagmon -1
     Move window to next monitor (keep tags)        MOD + Control + Next               :moonctl tagmonkt -1

### WINDOW MANAGEMENT ###
  # All of the hjkl bindings also work with arrow keys
     Focus window to the left/down/up/right         MOD + { h, j, k, l }
  # On tiled clients/layouts:
     Switch master                                  MOD + Shift + { h, l }
     Move window up/down in stack list              MOD + Shift + { j, k }
     Change master factor (resize master)           MOD + Control + { h, l }
  # On floating clients/layouts:
     Move window left/down/up/right                 MOD + Shift + { h, j, k, l }
     Resize window                                  MOD + Control + { h, j, k, l }
  # On floating and tiling:
     Resize window by drawing it                    MOD + r                            :moonctl rioresize
     Reset all tiled sizing hints                   MOD + Shift + r
     Focus next client                              MOD + space                        :moonctl focusnext 2001
     Close window                                   MOD + Shift + q                    :moonctl killclient
  # On any tag
     Increase number of windows in master area      MOD + a                            :moonctl incnmaster 1
     Decrease number of windows in master area      MOD + x                            :moonctl incnmaster -1

### LAYOUTS ###
     Default tiling layout                          MOD + t                            :moonctl setlayout 0
     Deck layout                                    MOD + c                            :moonctl setlayout 1
     Monocle layout                                 MOD + m                            :moonctl setlayout 2
     Floating layout                                MOD + Shift + f                    :moonctl setlayout 3
     Mirrored tiling layout                         MOD + Shift + t                    :moonctl setlayout 4
     Bottom tiling layout                           MOD + Control + t                  :moonctl setlayout 5
     Grid layout                                    MOD + Shift + t                    :moonctl setlayout 6
     Toggle floating for window                     MOD + Shift + space                :moonctl togglefloating
     Center floating window                         MOD + z                            :moonctl center

### APPS AND MENUS ###
     Open terminal                                  MOD + Return                       :\$TERMINAL
     Open browser                                   MOD + w                            :\$BROWSER
     Open file manager                              MOD + b                            :\$FILEMANAGER
     Open launcher/dmenu                            MOD + d                            :\$DMENUCMD
     Open menu                                      Control + Alt + Delete             :moonwm-menu 3

### OTHER ###
     Screenshot (select area)                       MOD + Print                        :moonwm-utils screenshot
     Screenshot whole screen                        MOD + Print                        :moonwm-utils screenshot screen
     Screenshot focused window                      MOD + Print                        :moonwm-utils screenshot focused
     Log out                                        Control + MOD + BackSpace          :moonctl quit

### FUNCTION KEYS ###
     Toggle top bar                                 MOD + F1                           :moonctl togglebar
     Toggle gaps between windows                    MOD + F2                           :moonctl togglegaps
     Reload styling from xrdb                       MOD + F5                           :moonwm-utils xrdb
     This menu                                      MOD + F11                          :moonwm-helper
"

echo "$options" | moonwm-utils dmenu -p Help: -l 30 | grep ':' | sed 's/.*://'| sh
